(function (_4TellBoost, $, undefined) {
    _4TellBoost.CONFIG = {
        SiteInfo: {
            baseURL: "",
            alias: "",
            GA_UA: "",
            GATrackID: "4TellRecs",
            addCartMethod: "",
            addCartImage: "",
            spacerImage: "",
            emptyImage: "_4TellBoost.loadpath + images/nophoto.gif",
            addCartClass: "addCartClass",
            priceClass: "",
            strikePriceClass: "strikePrice",
            salePriceClass: "",
            pricePrefix: "",
            salePricePrefix: "prefix",
            hideIfNoImage: true,
            minPrice: "$.01",
            custom: true,
            includeBase: true,
            delay: false,
            ABTesting: 0,
            persistentTesting: true,
            timeOut: 4000,
            addCartBtnAtts: "",
            platform: "4Tell3d.js",
            siteEnable: true,
            loadDelayObject: "",
            loadDelayTime: 0,
            blobId: 0,
            noConflict: false
        },
        PageSettings: {
            Home: [{
                id: 0,
                enable: true,
                showCaption: true,
                showImage: true,
                showTitle: true,
                showPrice: true,
                showRatings: true,
                showBuyButton: true,
                setHeight: false,
                setWidth: false,
                maxImageHeight: 0,
                numRows: 1,
                inFrame: false,
                resultType: 0,
                carousel: {
                    items: 0,
                    itemsCustom: "",
                    scrollPerPage: true,
                    navigation: false,
                    navigationText: false,
                    pagination: false
                },
                numItems: 1,
                startPos: 1,
                rotateRecs: false,
                recs: "",
                currentDisplayMode: "1",
                fillMode: "all",
                divSelect: "",
                divPosition: "append",
                caption: "Customers also bought...",
                captionStyle: "product4TCaption",
                productStyle: "product4T",
                productImageStyle: "productImage",
                productTitleStyle: "productTitle",
                imageQuery: "",
                responsive: {},
                rawJS: {},
                wrapper: "",
                outerTable: "",
                testGroup: {},
                imageSize: "&maxx=180&maxy=180",
                inCart: false
            }]      
        }
    }
} (window._4TellBoost = window._4TellBoost || {}, jQuery));

